/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package foo.bar

class App {

    void run(String[] args) {
        println "Hello world!"
    }

    static void main(String[] args) {
        new App().run()
    }
}
